import Head from 'next/head'
import Hero from '../components/Home/Hero'
import NavBar from '../components/Home/NavBar'

export default function Home() {
  return (
    <div className='bg-black h-screen p-5'>
      <Head>
        <title>Artist Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <NavBar />
      <Hero/>
    </div>
  )
}
