import Head from 'next/head'
import Features from '../components/Home/Features'
import Hero from '../components/Home/Hero'
import NavBar from '../components/layouts/NavBar'

export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Artist Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Hero />
      <Features/>
    </div>
  )
}
